#!/bin/bash

go ()
{
    if [[ $1 == 997 ]]; then
        cygstart "C:/Users/Owner/Dropbox/Math/Combinatorics/probabilistic_method/notes/main.tex"
    fi
    if [[ $1 == 783 ]]; then
        cygstart "C:/Users/Owner/Dropbox/Math/Number theory/Elliptic_curves/18.783"
    fi
    if [[ $1 == 750 ]]; then
        cygstart "http://www.750words.com"
    fi
    if [[ $1 == 404 ]]; then
        cygstart "C:/Users/Owner/Dropbox/Math/Computation/Computability and computational complexity/18.404/main.pdf"
    fi
    if [[ $1 == wf ]]; then
        cygstart "http://www.workflowy.com"
    fi
    if [[ $1 == temp ]]; then
        cygstart "C:/Users/Owner/Dropbox/Math/templates"
    fi
    if [[ $1 == sch ]]; then
        cygstart "C:/Users/Owner/Dropbox/Math/Geometry/algebraic_geometry/FOAGjun1113public.pdf"
    fi
    if [[ $1 == sc ]]; then
        cygstart "C:/Users/Owner/Dropbox/CS/hs/scripts/in.txt"
    fi
    if [[ $1 == py ]]; then
        cygstart "C:/Users/Owner/Dropbox/CS/Python Study Guide.docx"
    fi
    if [[ $1 == nt ]]; then
        cygstart "C:/Users/Owner/Dropbox/Math/Number theory/textbook/number-theory.pdf"
    fi
    if [[ $1 == ns ]]; then
        cygstart "C:/Users/Owner/Dropbox/Math/Combinatorics/probabilistic_method/noise_sensitivity2.pdf"
    fi
    if [[ $1 == new ]]; then
        cygstart "C:/Users/Owner/Music/Playlists/NewgroundsAll.wpl"
    fi
    if [[ $1 == mac ]]; then
        cygstart "C:/Users/Owner/Dropbox/Math/templates/macros.tex"
    fi
    if [[ $1 == lyx ]]; then
        cygstart "C:/Program Files (x86)/LyX20/bin/LyX.exe"
    fi
    if [[ $1 == la ]]; then
        cygstart "C:/Users/Owner/Dropbox/Math/Algebra/linear_algebra/Linear Algebra Notes2.pdf"
    fi
    if [[ $1 == habit ]]; then
        cygstart "C:/Users/Owner/Dropbox/Learning/life/habit queue.xlsx"
    fi
    if [[ $1 == gen ]]; then
        cygstart "https://www.sharelatex.com/project/542d9d098edf8b10736d60cb"
    fi
    if [[ $1 == f ]]; then
        cygstart "C:/Users/Owner/Dropbox/Math/Analysis/functional/part_iii_functional.pdf"
    fi
    if [[ $1 == em ]]; then
        cygstart "http://www.gmail.com"
    fi
    if [[ $1 == ec ]]; then
        cygstart "C:/Users/Owner/Dropbox/Math/Number theory/Elliptic_curves"
    fi
    if [[ $1 == dp ]]; then
        cygstart "C:/Users/Owner/Dropbox"
    fi
    if [[ $1 == dist ]]; then
        cygstart "C:/Users/Owner/Dropbox/Math/Analysis/functional/part_iii_distributions.pdf"
    fi
    if [[ $1 == detex ]]; then
        cygstart "http://detexify.kirelabs.org/classify.html"
    fi
    if [[ $1 == cpx ]]; then
        cygstart "C:/Users/Owner/Dropbox/Math/Computation/Computability and computational complexity/complexity.tex"
    fi
    if [[ $1 == cp ]]; then
        cygstart "C:/Users/Owner/Dropbox/Math/Computation"
    fi
    if [[ $1 == cd ]]; then
        cygstart "C:/Users/Owner/Dropbox/Math/Reference/LaTeX/CDGuide.pdf"
    fi
    if [[ $1 == combo ]]; then
        cygstart "C:/Users/Owner/Dropbox/Math/Combinatorics/probabilistic_method/part_iii_combo.pdf"
    fi
    if [[ $1 == comb ]]; then
        cygstart "C:/Users/Owner/Dropbox/Math/Combinatorics"
    fi
    if [[ $1 == cod ]]; then
        cygstart "C:/Users/Owner/Dropbox/Math/Computation/Coding"
    fi
    if [[ $1 == bash ]]; then
        cygstart "C:/cygwin64/home/Owner/.bashrc"
    fi
    if [[ $1 == amit ]]; then
        cygstart "C:/Users/Owner/Dropbox/Math/Number theory/finite_fields/AMiIT_review.pdf"
    fi
    if [[ $1 == alg ]]; then
        cygstart "C:/Users/Owner/Dropbox/Math/Computation/Algorithms/algorithms.tex"
    fi
    if [[ $1 == al ]]; then
        cygstart "C:/Users/Owner/Dropbox/Math/Computation/Algorithms"
    fi
    if [[ $1 == a ]]; then
        cygstart "C:/Users/Owner/Dropbox/Math/Algebra/abstract_algebra/Algebra Notes.pdf"
    fi
}