#!/bin/bash

if [[ $1 == 997 ]]; then
    cd "C:/Users/holden-lee/Dropbox/Math/Combinatorics/probabilistic_method/notes/main.tex"
fi
if [[ $1 == 965 ]]; then
    cd "C:/Users/holden-lee/Dropbox/Math/Geometry/riemannian/18.965/main.pdf"
fi
if [[ $1 == 783 ]]; then
    cd "C:/Users/holden-lee/Dropbox/Math/Number theory/Elliptic_curves/18.783"
fi
if [[ $1 == 750 ]]; then
    cd "http://www.750words.com"
fi
if [[ $1 == 404 ]]; then
    cd "C:/Users/holden-lee/Dropbox/Math/Computation/Computability and computational complexity/18.404/main.pdf"
fi
if [[ $1 == wf ]]; then
    cd "http://www.workflowy.com"
fi
if [[ $1 == txt ]]; then
    cd "C:/Users/holden-lee/Dropbox/Math/Number theory/textbook"
fi
if [[ $1 == to ]]; then
    cd "https://workflowy.com/#/35faf5a77453"
fi
if [[ $1 == th ]]; then
    cd "C:/Users/holden-lee/Dropbox/Math/thread.tex"
fi
if [[ $1 == temp ]]; then
    cd "C:/Users/holden-lee/Dropbox/Math/templates"
fi
if [[ $1 == scr ]]; then
    cd "C:/Users/holden-lee/Dropbox/CS/scripts"
fi
if [[ $1 == sch ]]; then
    cd "C:/Users/holden-lee/Dropbox/Math/Geometry/algebraic_geometry/FOAGjun1113public.pdf"
fi
if [[ $1 == sc ]]; then
    cd "C:/Users/holden-lee/Dropbox/CS/scripts/in.txt"
fi
if [[ $1 == py ]]; then
    cd "C:/Users/holden-lee/Dropbox/CS/Python Study Guide.docx"
fi
if [[ $1 == pr6 ]]; then
    cd "C:/Program Files (x86)"
fi
if [[ $1 == pr ]]; then
    cd "C:/Program Files"
fi
if [[ $1 == nt ]]; then
    cd "C:/Users/holden-lee/Dropbox/Math/Number theory/textbook/number-theory.pdf"
fi
if [[ $1 == ns ]]; then
    cd "C:/Users/holden-lee/Dropbox/Math/Combinatorics/probabilistic_method/noise_sensitivity2.pdf"
fi
if [[ $1 == new ]]; then
    cd "C:/Users/holden-lee/Music/Playlists/NewgroundsAll.wpl"
fi
if [[ $1 == math ]]; then
    cd "C:/Users/holden-lee/Dropbox/Math"
fi
if [[ $1 == mac ]]; then
    cd "C:/Users/holden-lee/Dropbox/Math/templates/macros.tex"
fi
if [[ $1 == lyx ]]; then
    cd "C:/Program Files (x86)/LyX20/bin/LyX.exe"
fi
if [[ $1 == la ]]; then
    cd "C:/Users/holden-lee/Dropbox/Math/Algebra/linear_algebra/Linear Algebra Notes2.pdf"
fi
if [[ $1 == hs ]]; then
    cd "C:/Users/holden-lee/Dropbox/CS/hs"
fi
if [[ $1 == hott ]]; then
    cd "C:/Users/holden-lee/Dropbox/Math/Computation/HoTT.pdf"
fi
if [[ $1 == habit ]]; then
    cd "C:/Users/holden-lee/Dropbox/Learning/life/habit queue.xlsx"
fi
if [[ $1 == gen ]]; then
    cd "https://www.sharelatex.com/project/542d9d098edf8b10736d60cb"
fi
if [[ $1 == fb ]]; then
    cd "http://www.facebook.com"
fi
if [[ $1 == f ]]; then
    cd "C:/Users/holden-lee/Dropbox/Math/Analysis/functional/part_iii_functional.pdf"
fi
if [[ $1 == em ]]; then
    cd "http://www.gmail.com"
fi
if [[ $1 == elm ]]; then
    cd "C:/Users/holden-lee/Dropbox/CS/hs/elm"
fi
if [[ $1 == ec ]]; then
    cd "C:/Users/holden-lee/Dropbox/Math/Number theory/Elliptic_curves"
fi
if [[ $1 == dvir ]]; then
    cd "C:/Users/holden-lee/Dropbox/Math/Computation/Computability and computational complexity/dvir"
fi
if [[ $1 == db ]]; then
    cd "C:/Users/holden-lee/Dropbox"
fi
if [[ $1 == dl ]]; then
    cd "C:/Users/holden-lee/Downloads"
fi
if [[ $1 == dist ]]; then
    cd "C:/Users/holden-lee/Dropbox/Math/Analysis/functional/part_iii_distributions.pdf"
fi
if [[ $1 == detex ]]; then
    cd "http://detexify.kirelabs.org/classify.html"
fi
if [[ $1 == cs ]]; then
    cd "C:/Users/holden-lee/Dropbox/CS"
fi
if [[ $1 == cpx ]]; then
    cd "C:/Users/holden-lee/Dropbox/Math/Computation/Computability and computational complexity/complexity.tex"
fi
if [[ $1 == cp ]]; then
    cd "C:/Users/holden-lee/Dropbox/Math/Computation"
fi
if [[ $1 == cd ]]; then
    cd "C:/Users/holden-lee/Dropbox/Math/Reference/LaTeX/CDGuide.pdf"
fi
if [[ $1 == combo ]]; then
    cd "C:/Users/holden-lee/Dropbox/Math/Combinatorics/probabilistic_method/part_iii_combo.pdf"
fi
if [[ $1 == comb ]]; then
    cd "C:/Users/holden-lee/Dropbox/Math/Combinatorics"
fi
if [[ $1 == cod ]]; then
    cd "C:/Users/holden-lee/Dropbox/Math/Computation/Coding"
fi
if [[ $1 == cal ]]; then
    cd "https://www.google.com/calendar/render?pli=1#g"
fi
if [[ $1 == btc ]]; then
    cd "C:/Users/holden-lee/Dropbox/Math/Computation/Cryptography/Bitcoin"
fi
if [[ $1 == bash ]]; then
    cd "C:/cygwin64/home/holden-lee/.bashrc"
fi
if [[ $1 == an ]]; then
    cd "C:/Users/holden-lee/Dropbox/Math/Analysis"
fi
if [[ $1 == amit ]]; then
    cd "C:/Users/holden-lee/Dropbox/Math/Number theory/finite_fields/AMiIT_review.pdf"
fi
if [[ $1 == alg ]]; then
    cd "C:/Users/holden-lee/Dropbox/Math/Computation/Algorithms/algorithms.tex"
fi
if [[ $1 == al ]]; then
    cd "C:/Users/holden-lee/Dropbox/Math/Computation/Algorithms"
fi
if [[ $1 == actv ]]; then
    cd "C:/Users/holden-lee/Dropbox/Math/Number theory/Additive_combinatorics/Additive Combinatorics, Tao and Vu.pdf"
fi
if [[ $1 == ac ]]; then
    cd "C:/Users/holden-lee/Dropbox/Math/Number theory/Additive_combinatorics/Additive combinatorics/main.pdf"
fi
if [[ $1 == a ]]; then
    cd "C:/Users/holden-lee/Dropbox/Math/Algebra/abstract_algebra/Algebra Notes.pdf"
fi
