#!/bin/bash

cd "C:/Users/holden-lee/Dropbox/CS/scripts/"
sed -i 's/\\/\//g' in.txt
shortcuts in.txt g
dos2unix g
cp g c
sed -i 's/cygstart/cd/g' c
dos2unix c

#big computer
cp g go
cp c cdt
sed -i 's/Owner/holden-lee/g' go
sed -i 's/Owner/holden-lee/g' cdt
dos2unix go
dos2unix cdt

cp setenv setenv2
sed -i 's/Owner/holden-lee/g' setenv2
setenv2
